"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:surface)\
$os\
$username\
[](bg:overlay fg:surface)\
$directory\
[](bg:muted fg:overlay)\
$git_branch\
$git_status\
[](fg:muted bg:subtext)\
$c\
$rust\
$golang\
$nodejs\
$bun\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:subtext bg:iris)\
$conda\
[](fg:iris bg:rose)\
$time\
[ ](fg:rose)\
$cmd_duration\
$line_break\
$character"""

palette = 'rose_pine_moon'

[os]
disabled = false
style = "bg:surface fg:iris"

[os.symbols]
Windows = ""
Ubuntu = "  "
SUSE = ""
Raspbian = "  "
Mint = "  "
Macos = "  "
Manjaro = ""
Linux = "  "
Gentoo = "  "
Fedora = "  "
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "  "
Artix = "  "
CentOS = ""
Debian = "  "
Redhat = "  "
RedHatEnterprise = "  "

[username]
show_always = true
style_user  = "bg:surface fg:text"
style_root  = "bg:surface fg:rose"
format = '[ $user]($style)'

[directory]
style             = "bg:overlay fg:iris"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "   "
"Downloads" = " "
"Music" = "   "
"Pictures" = " "
"Developer" = "   "

[git_branch]
symbol = ""
style = "bg:muted"
format = '[[ $symbol $branch ](fg:iris bg:muted)]($style)'

[git_status]
style  = "bg:muted"
format = '[[($all_status$ahead_behind )](fg:rose bg:muted)]($style)'

[nodejs]
symbol = ""
style  = "bg:subtext"
format = '[[ $symbol( $version) ](fg:text bg:subtext)]($style)'

[bun]
symbol = ""
style  = "bg:subtext"
format = '[[ $symbol( $version) ](fg:text bg:subtext)]($style)'

[c]
symbol = " "
style  = "bg:subtext"
format = '[[ $symbol( $version) ](fg:text bg:subtext)]($style)'

[rust]
symbol = ""
style  = "bg:subtext"
format = '[[ $symbol( $version) ](fg:text bg:subtext)]($style)'

[golang]
symbol = ""
style  = "bg:subtext"
format = '[[ $symbol( $version) ](fg:text bg:subtext)]($style)'

[php]
style  = "bg:subtext"
format = '[[ $symbol( $version) ](fg:text bg:subtext)]($style)'

[java]
symbol = " "
style  = "bg:subtext"
format = '[[ $symbol( $version) ](fg:text bg:subtext)]($style)'

[kotlin]
symbol = ""
style  = "bg:subtext"
format = '[[ $symbol( $version) ](fg:text bg:subtext)]($style)'

[haskell]
style  = "bg:subtext"
format = '[[ $symbol( $version) ](fg:text bg:subtext)]($style)'

[python]
symbol = ""
style  = "bg:subtext"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:text bg:subtext)]($style)'

[docker_context]
symbol = ""
style = "bg:foam"
format = '[[ $symbol( $context) ](fg:mantle bg:foam)]($style)'

[conda]
symbol = "  "
style   = "fg:mantle bg:iris"
format  = '[$symbol$environment ]($style)'
ignore_base = false

[time]
disabled = false
time_format = "%R"
style = "bg:rose"
format = '[[  $time ](fg:mantle bg:rose)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:iris)'
error_symbol = '[❯](bold fg:love)'
vimcmd_symbol = '[❮](bold fg:iris)'
vimcmd_replace_one_symbol = '[❮](bold fg:rose)'
vimcmd_replace_symbol = '[❮](bold fg:rose)'
vimcmd_visual_symbol = '[❮](bold fg:subtext)'

[cmd_duration]
show_milliseconds = true
format = " in $duration "
style = "fg:subtext"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.rose_pine_moon]
base    = "#232136" # Mocha Base alternative
mantle  = "#2a283e" # Inverse element labels (replaces crust)
surface = "#393552" # Dark powerline block 1
overlay = "#4a4664" # Dark powerline block 2
muted   = "#565274" # Dark powerline block 3
subtext = "#6e6a86" # Code module track background
text    = "#e0def4" # Crisp default lettering
iris    = "#c4a7e7" # Primary Hollow Knight purple glow
rose    = "#ea9a97" # Soft contrast magenta
love    = "#eb6f92" # Core failure/error red indicator
gold    = "#f6c177" # Warning asset mapping
foam    = "#9ccfd8" # Secondary accent block
pine    = "#3e8fb0" # Deep highlight green
