# ===== VELOCITY - Hypridle Config =====
# Theme: Rosé Pine Moon (Mocha-like Dark)

general {
    lock_cmd = hyprlock --grace 2                   # Command called when requesting lock
    before_sleep_cmd = hyprlock --grace 2             # Lock screen securely before suspension
    after_sleep_cmd = hyprctl dispatch dpms on  # Assure screens fire up nicely post-sleep
    ignore_dbus_inhibit = false
}

